# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  alyveljidesigns.com:
    site_hosts:
      - canonical: alyveljidesigns.test
        redirects:
          - www.alyveljidesigns.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: ty@bonlandocreative.com
    admin_user: tybohnet
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
