# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: "u%T@Um![KXB62J"

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: ":w$_Kagd8:=&4&^z"
    salt: "Fu[wN]L6g)=@:mr"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  alyvelji.bonlando-digital.com:
    env:
      db_password: "Bf9kq3X/9z8.@%"
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "TK.41?V(XZf]X]DQmUfGs:x&j>.Y1?i(P|B5k?L)QZ2IG$!kjyr=V]]j7WY/zq;O"
      secure_auth_key: "ScMx*sD]2g@@^/4M70F4K,/h#tG!Y)YpqJuLO#Fwy%zc3rtRvH;}pKLz?E=Z3G=V"
      logged_in_key: "nO%)yJ^PZ#:D$BDx2[s#*ml4NaK`XYywlmWq$o:A0AO`g%lZ2Y00U%-G(5w67^cj"
      nonce_key: "l2jw%n3|bRGz%Q]}Gbfo]#S^,`mu>8L)c[OHPfSXU@75cDH9NBtZ=[%MVpE-ds4L"
      auth_salt: "L]&A=,`Y/juC#)+):`k|xGOnP2hIRkp{oVd-8gO,vkAK_/N|v3IxXQPxx(2*//3a"
      secure_auth_salt: "s]>Ji923E|>TFpP?m^-3]x99fa(/yP@_GqB#)xAuZ<o>oZ+[iJV>x2esOxN)m?]T"
      logged_in_salt: "J=Dqo2$}RM)tsD:X>JR4@.KVw9tyfm#[}rn_<%pQXnj+s#l6%9-0:6VG6;OIyqZL"
      nonce_salt: "[{V_dQyBeg729B$F2v<u&^VhT:KIv2J(ChIYo@<B[a)$ruv2t[S<0Vw|ogOCs!3b"
